In [2]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv("powerplant_data.csv")

In [4]:
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [5]:
#AT-temperature 
#v- vaccuum 
#AP-pressure 
#RH- humidity 
#PE-produced energy

In [6]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [7]:
X=df.drop("PE",axis=1)
y=df["PE"]

In [8]:
X.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [9]:
#split data 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [11]:
import torch 
import torch.nn as nn

In [12]:
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)
X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.float32).view(-1,1)

In [13]:
type(X_train_scaled)

numpy.ndarray

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
from torch.utils.data import TensorDataset,DataLoader
train_dataset=TensorDataset(X_train_tensor,y_train_tensor)
test_dataset=TensorDataset(X_test_tensor,y_test_tensor)

In [16]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

<h1>Deep Learning </h1>

In [17]:
#define an ANN model 
#in form of a class
class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()
        self.model=nn.Sequential(
            #1st hidden layer 
            nn.Linear(X_train.shape[1],6),
            nn.ReLU(),
            
            #2nd hidden
            nn.Linear(6,6),
            nn.ReLU(),
            
            #output layer 
            nn.Linear(6,1),
        )
    def forward(self,x):
        return self.model(x)

In [18]:
import torch.optim as optim
model=ANN()
#loss,optimizer
crietron=nn.MSELoss()
optimizer=optim.Adam(model.parameters())

In [19]:
#train the model 
train_losses=[]
valid_losses=[]
best_val_loss = float("inf")
epochs=100
for epoch in range(epochs):
    model.train()
    running_loss=0.0 #1 epoch training loss
    for xb,yb in train_loader:
        #xb- features of 1 batch 
        #yb-labels of 1 batch 
        optimizer.zero_grad()
        
        outputs=model(xb)#predicted outputs
        loss = crietron(outputs,yb) #compute loss
        loss.backward()#compute gradient
        optimizer.step() #params update 
        
        running_loss += loss.item() #loss is a tensor -> py float
        
    epoch_train_loss=running_loss/len(train_loader)
    train_losses.append(epoch_train_loss)

    #validation
    running_val_loss=0.0
    with torch.no_grad():
        for xb,yb in test_loader:
            outputs=model(xb)
            loss = crietron(outputs,yb)
            running_val_loss += loss
    epoch_val_loss=running_val_loss/len(test_loader)
    valid_losses.append(epoch_val_loss)
    print(f"epoch ${epoch+1}/{epochs} ==> train loss= ${epoch_train_loss} &val_loss= ${epoch_val_loss}")
    if epoch_val_loss<best_val_loss:
        best_val_loss=epoch_val_loss
        torch.save(model.state_dict(),"best_model.pt")

epoch $1/100 ==> train loss= $206530.50911458334 &val_loss= $205350.765625
epoch $2/100 ==> train loss= $201544.68697916667 &val_loss= $195035.734375
epoch $3/100 ==> train loss= $182788.63411458334 &val_loss= $166867.5625
epoch $4/100 ==> train loss= $144297.38076171876 &val_loss= $120313.4453125
epoch $5/100 ==> train loss= $95368.32700195312 &val_loss= $73171.1953125
epoch $6/100 ==> train loss= $55560.09768880208 &val_loss= $42329.7578125
epoch $7/100 ==> train loss= $33764.50196940104 &val_loss= $28159.8359375
epoch $8/100 ==> train loss= $24419.408744303386 &val_loss= $21803.810546875
epoch $9/100 ==> train loss= $19699.575594075523 &val_loss= $18056.224609375
epoch $10/100 ==> train loss= $16501.416467285155 &val_loss= $15012.10546875
epoch $11/100 ==> train loss= $13594.826696777343 &val_loss= $12185.9853515625
epoch $12/100 ==> train loss= $10857.231730143229 &val_loss= $9463.9521484375
epoch $13/100 ==> train loss= $8267.186938476563 &val_loss= $7010.80908203125
epoch $14/100 ==> train loss= $6007.335349527994 &val_loss= $5015.9326171875
epoch $15/100 ==> train loss= $4252.125280253093 &val_loss= $3528.462158203125
epoch $16/100 ==> train loss= $2981.427675374349 &val_loss= $2476.503173828125
epoch $17/100 ==> train loss= $2070.1261171976726 &val_loss= $1746.4295654296875
epoch $18/100 ==> train loss= $1451.891944885254 &val_loss= $1250.5377197265625
epoch $19/100 ==> train loss= $1036.7995816548666 &val_loss= $911.9622192382812
epoch $20/100 ==> train loss= $755.4749626159668 &val_loss= $675.8873901367188
epoch $21/100 ==> train loss= $553.7828561782837 &val_loss= $501.9364013671875
epoch $22/100 ==> train loss= $405.97923272450765 &val_loss= $371.4958801269531
epoch $23/100 ==> train loss= $298.6830113093058 &val_loss= $275.5263366699219
epoch $24/100 ==> train loss= $220.02702547709148 &val_loss= $207.0328826904297
epoch $25/100 ==> train loss= $164.37060855229694 &val_loss= $156.9031219482422
epoch $26/100 ==> train loss= $126.44873456954956 &val_loss= $124.64075469970703
epoch $27/100 ==> train loss= $100.12992304166158 &val_loss= $100.42729949951172
epoch $28/100 ==> train loss= $80.80677692890167 &val_loss= $82.42465209960938
epoch $29/100 ==> train loss= $66.13093455632527 &val_loss= $67.381591796875
epoch $30/100 ==> train loss= $54.80854090452194 &val_loss= $55.63626480102539
epoch $31/100 ==> train loss= $46.107772155602774 &val_loss= $46.84375
epoch $32/100 ==> train loss= $39.2072566986084 &val_loss= $40.02798843383789
epoch $33/100 ==> train loss= $33.94398454427719 &val_loss= $34.024513244628906
epoch $34/100 ==> train loss= $30.28090509176254 &val_loss= $30.37732696533203
epoch $35/100 ==> train loss= $27.459325619538625 &val_loss= $27.18861198425293
epoch $36/100 ==> train loss= $25.77121106386185 &val_loss= $25.17060661315918
epoch $37/100 ==> train loss= $24.58583772381147 &val_loss= $23.783536911010742
epoch $38/100 ==> train loss= $23.906549787521364 &val_loss= $23.282936096191406
epoch $39/100 ==> train loss= $23.260419698556266 &val_loss= $22.345672607421875
epoch $40/100 ==> train loss= $22.84405978520711 &val_loss= $21.92245864868164
epoch $41/100 ==> train loss= $22.58890995581945 &val_loss= $21.073917388916016
epoch $42/100 ==> train loss= $22.273465740680695 &val_loss= $20.939586639404297
epoch $43/100 ==> train loss= $22.18016049464544 &val_loss= $20.613508224487305
epoch $44/100 ==> train loss= $21.89694081743558 &val_loss= $21.384611129760742
epoch $45/100 ==> train loss= $21.828911034266152 &val_loss= $20.78672218322754
epoch $46/100 ==> train loss= $21.76244193315506 &val_loss= $20.198108673095703
epoch $47/100 ==> train loss= $21.689054214954375 &val_loss= $20.231294631958008
epoch $48/100 ==> train loss= $21.6334924419721 &val_loss= $20.610506057739258
epoch $49/100 ==> train loss= $21.626653782526652 &val_loss= $20.202680587768555
epoch $50/100 ==> train loss= $21.586311050256093 &val_loss= $19.975339889526367
epoch $51/100 ==> train loss= $21.452617331345877 &val_loss= $20.070558547973633
epoch $52/100 ==> train loss= $21.41527349750201 &val_loss= $19.962114334106445
epoch $53/100 ==> train loss= $21.45339020093282 &val_loss= $19.961524963378906
epoch $54/100 ==> train loss= $21.520659482479097 &val_loss= $20.17804527282715
epoch $55/100 ==> train loss= $21.48747052748998 &val_loss= $20.804920196533203
epoch $56/100 ==> train loss= $21.453293800354004 &val_loss= $19.85328483581543
epoch $57/100 ==> train loss= $21.451397407054902 &val_loss= $20.0853271484375
epoch $58/100 ==> train loss= $21.473606618245444 &val_loss= $19.703216552734375
epoch $59/100 ==> train loss= $21.507896729310353 &val_loss= $19.72528076171875
epoch $60/100 ==> train loss= $21.62919497092565 &val_loss= $20.048065185546875
epoch $61/100 ==> train loss= $21.366313354174295 &val_loss= $19.66848373413086
epoch $62/100 ==> train loss= $21.54425279100736 &val_loss= $20.058250427246094
epoch $63/100 ==> train loss= $21.36733720302582 &val_loss= $19.893213272094727
epoch $64/100 ==> train loss= $21.32255911628405 &val_loss= $19.955114364624023
epoch $65/100 ==> train loss= $21.369040046135584 &val_loss= $20.17434310913086
epoch $66/100 ==> train loss= $21.44705640077591 &val_loss= $20.02398109436035
epoch $67/100 ==> train loss= $21.467654979228975 &val_loss= $19.720661163330078
epoch $68/100 ==> train loss= $21.45165055990219 &val_loss= $19.967561721801758
epoch $69/100 ==> train loss= $21.368948578834534 &val_loss= $20.36246681213379
epoch $70/100 ==> train loss= $21.38803582986196 &val_loss= $20.346891403198242
epoch $71/100 ==> train loss= $21.437068035205204 &val_loss= $20.737947463989258
epoch $72/100 ==> train loss= $21.46799306869507 &val_loss= $19.573646545410156
epoch $73/100 ==> train loss= $21.50136319001516 &val_loss= $19.676616668701172
epoch $74/100 ==> train loss= $21.54241924683253 &val_loss= $20.919055938720703
epoch $75/100 ==> train loss= $21.619813640912373 &val_loss= $19.683399200439453
epoch $76/100 ==> train loss= $21.358322501182556 &val_loss= $19.68509292602539
epoch $77/100 ==> train loss= $21.41891482671102 &val_loss= $19.58744239807129
epoch $78/100 ==> train loss= $21.460888504981995 &val_loss= $19.654640197753906
epoch $79/100 ==> train loss= $21.411596337954204 &val_loss= $19.826459884643555
epoch $80/100 ==> train loss= $21.36962806781133 &val_loss= $19.617107391357422
epoch $81/100 ==> train loss= $21.30534397761027 &val_loss= $20.342662811279297
epoch $82/100 ==> train loss= $21.41403712828954 &val_loss= $19.734424591064453
epoch $83/100 ==> train loss= $21.245200049877166 &val_loss= $20.148412704467773
epoch $84/100 ==> train loss= $21.37472688158353 &val_loss= $19.70130157470703
epoch $85/100 ==> train loss= $21.314094225565594 &val_loss= $20.039949417114258
epoch $86/100 ==> train loss= $21.33624805609385 &val_loss= $20.08101463317871
epoch $87/100 ==> train loss= $21.36505308945974 &val_loss= $19.70261573791504
epoch $88/100 ==> train loss= $21.498649996519088 &val_loss= $19.886749267578125
epoch $89/100 ==> train loss= $21.510188229878743 &val_loss= $19.83821678161621
epoch $90/100 ==> train loss= $21.46612972021103 &val_loss= $20.100095748901367
epoch $91/100 ==> train loss= $21.29004820982615 &val_loss= $19.60493278503418
epoch $92/100 ==> train loss= $21.60175354083379 &val_loss= $19.914602279663086
epoch $93/100 ==> train loss= $21.519666182994843 &val_loss= $20.253726959228516
epoch $94/100 ==> train loss= $21.47829237381617 &val_loss= $19.53045654296875
epoch $95/100 ==> train loss= $21.433383683363598 &val_loss= $19.792009353637695
epoch $96/100 ==> train loss= $21.36945629119873 &val_loss= $19.71691131591797
epoch $97/100 ==> train loss= $21.364493215084075 &val_loss= $19.84554672241211
epoch $98/100 ==> train loss= $21.45278687874476 &val_loss= $20.21800422668457
epoch $99/100 ==> train loss= $21.353689877192178 &val_loss= $19.717378616333008
epoch $100/100 ==> train loss= $21.404611690839133 &val_loss= $19.544462203979492

In [20]:
#evaluation
model.eval()
with torch.no_grad():
    train_preds=model(X_train_tensor)
    test_preds=model(X_test_tensor)
    train_mse_loss=crietron(train_preds,y_train_tensor)
    test_mse_loss=crietron(test_preds,y_test_tensor)
print("training MSE: ",train_mse_loss.item())
print("testing MSE: ",test_mse_loss.item())

training MSE:  21.14922523498535
testing MSE:  19.55259895324707

In [21]:
from sklearn.metrics import r2_score
print("r^2 score=",r2_score(y_test,test_preds))

r^2 score= 0.9316687102043394